ARG version
FROM almalinux:${version:-8}
ARG COURSE=docker
ARG TRAINER=vinay
#RUN cat /etc/*release
ENV Duration=120HRS
RUN echo "Course is: ${COURSE}, Trainer is: ${TRAINER}, Duration is:${Duration}"
CMD [ "sleep","100" ]